"""
Hardcoded demo products — used when OPENAI_API_KEY is not set.
Matches the same shape the frontend expects.
"""

DEMO_PRODUCTS = [
    {
        "id": "1",
        "name": "Coca-Cola Original 600ml",
        "brand": "Coca-Cola",
        "category": "Bebidas",
        "healthScore": 15,
        "calories": 252,
        "sugar_g": 63,
        "sodium_mg": 50,
        "fat_g": 0,
        "saturated_fat_g": 0,
        "fiber_g": 0,
        "protein_g": 0,
        "sellos": ["EXCESO CALORÍAS", "EXCESO AZÚCARES"],
        "recommendation": "Altísimo en azúcar. Considera agua mineral o agua natural como alternativa.",
        "bbox": {"x": 5, "y": 10, "w": 18, "h": 35},
    },
    {
        "id": "2",
        "name": "Sabritas Original 45g",
        "brand": "Sabritas",
        "category": "Botanas",
        "healthScore": 28,
        "calories": 230,
        "sugar_g": 1,
        "sodium_mg": 180,
        "fat_g": 15,
        "saturated_fat_g": 2,
        "fiber_g": 1,
        "protein_g": 2,
        "sellos": ["EXCESO CALORÍAS", "EXCESO SODIO", "EXCESO GRASAS SATURADAS"],
        "recommendation": "Alto en calorías, sodio y grasas. Para botana más ligera prueba cacahuates naturales o jícama.",
        "bbox": {"x": 25, "y": 8, "w": 18, "h": 30},
    },
    {
        "id": "3",
        "name": "Bimbo Integral",
        "brand": "Bimbo",
        "category": "Pan",
        "healthScore": 55,
        "calories": 65,
        "sugar_g": 3,
        "sodium_mg": 130,
        "fat_g": 1,
        "saturated_fat_g": 0.3,
        "fiber_g": 2.5,
        "protein_g": 3,
        "sellos": ["EXCESO SODIO"],
        "recommendation": "Opción moderada. Tiene fibra pero algo de sodio. Aceptable para un sándwich rápido.",
        "bbox": {"x": 48, "y": 12, "w": 16, "h": 28},
    },
    {
        "id": "4",
        "name": "Yoghurt Griego Lala Natural",
        "brand": "Lala",
        "category": "Lácteos",
        "healthScore": 78,
        "calories": 90,
        "sugar_g": 4,
        "sodium_mg": 45,
        "fat_g": 3,
        "saturated_fat_g": 2,
        "fiber_g": 0,
        "protein_g": 12,
        "sellos": [],
        "recommendation": "Buena fuente de proteína y bajo en azúcar. Una de las mejores opciones del estante.",
        "bbox": {"x": 68, "y": 10, "w": 14, "h": 32},
    },
    {
        "id": "5",
        "name": "Agua Ciel 600ml",
        "brand": "Ciel",
        "category": "Bebidas",
        "healthScore": 100,
        "calories": 0,
        "sugar_g": 0,
        "sodium_mg": 0,
        "fat_g": 0,
        "saturated_fat_g": 0,
        "fiber_g": 0,
        "protein_g": 0,
        "sellos": [],
        "recommendation": "La mejor opción para hidratarte. Sin calorías, sin azúcar, sin sellos.",
        "bbox": {"x": 85, "y": 8, "w": 12, "h": 35},
    },
    {
        "id": "6",
        "name": "Maruchan Habanero",
        "brand": "Maruchan",
        "category": "Sopas instantáneas",
        "healthScore": 12,
        "calories": 380,
        "sugar_g": 2,
        "sodium_mg": 1520,
        "fat_g": 16,
        "saturated_fat_g": 7,
        "fiber_g": 1,
        "protein_g": 8,
        "sellos": ["EXCESO CALORÍAS", "EXCESO SODIO", "EXCESO GRASAS SATURADAS", "EXCESO GRASAS TRANS"],
        "recommendation": "Extremadamente alto en sodio (76% del límite diario). Evita si puedes.",
        "bbox": {"x": 30, "y": 50, "w": 18, "h": 25},
    },
    {
        "id": "7",
        "name": "Barra Nature Valley Avena y Miel",
        "brand": "Nature Valley",
        "category": "Barras",
        "healthScore": 45,
        "calories": 190,
        "sugar_g": 12,
        "sodium_mg": 160,
        "fat_g": 6,
        "saturated_fat_g": 0.5,
        "fiber_g": 2,
        "protein_g": 4,
        "sellos": ["EXCESO CALORÍAS", "EXCESO AZÚCARES"],
        "recommendation": "Parece sana pero tiene bastante azúcar. Una opción intermedia para snack rápido.",
        "bbox": {"x": 55, "y": 52, "w": 16, "h": 22},
    },
    {
        "id": "8",
        "name": "Nuez mixta Del Monte 40g",
        "brand": "Del Monte",
        "category": "Botanas",
        "healthScore": 82,
        "calories": 200,
        "sugar_g": 2,
        "sodium_mg": 50,
        "fat_g": 18,
        "saturated_fat_g": 2,
        "fiber_g": 2,
        "protein_g": 5,
        "sellos": [],
        "recommendation": "Grasas saludables, proteína y fibra. Excelente snack aunque calórico — controla la porción.",
        "bbox": {"x": 75, "y": 48, "w": 14, "h": 26},
    },
]

DEMO_CHAT_RESPONSES = {
    "default": "Basado en los productos detectados en tu foto, puedo ayudarte a elegir mejores opciones. ¿Qué te gustaría saber?",
    "sana": "De los productos en el estante, las mejores opciones son:\n\n🟢 **Agua Ciel** (Score: 100) — Siempre la mejor opción para hidratarte.\n🟢 **Nuez mixta Del Monte** (Score: 82) — Grasas saludables y proteína.\n🟢 **Yoghurt Griego Lala** (Score: 78) — Alta proteína, bajo azúcar.\n\nEvita la Maruchan (Score: 12) y la Coca-Cola (Score: 15).",
    "azucar": "Productos ordenados por azúcar (de menos a más):\n\n🟢 Agua Ciel: 0g\n🟢 Sabritas: 1g\n🟡 Maruchan: 2g\n🟡 Nuez Del Monte: 2g\n🟡 Bimbo Integral: 3g\n🟡 Lala Griego: 4g\n🟠 Nature Valley: 12g ⚠️\n🔴 Coca-Cola: **63g** ⛔\n\nLa Coca-Cola tiene más de 15 cucharaditas de azúcar.",
    "proteina": "Para proteína, tus mejores opciones son:\n\n🥇 **Yoghurt Griego Lala** — 12g de proteína\n🥈 **Maruchan** — 8g pero con demasiado sodio\n🥉 **Nuez Del Monte** — 5g con grasas buenas\n\nSi buscas proteína sin sellos negativos, el yoghurt griego es la clara ganadora.",
    "sodio": "⚠️ Cuidado con el sodio en estos productos:\n\n🔴 **Maruchan**: 1,520mg (76% del límite diario)\n🟠 Sabritas: 180mg\n🟡 Nature Valley: 160mg\n🟡 Bimbo Integral: 130mg\n🟢 Coca-Cola: 50mg\n🟢 Nuez Del Monte: 50mg\n🟢 Lala Griego: 45mg\n🟢 Agua Ciel: 0mg\n\nLa Maruchan sola casi cubre tu límite diario de sodio.",
}